# Generated by Django 3.0.6 on 2020-05-15 09:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200515_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedata',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
