# Generated by Django 3.0.6 on 2020-05-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_sitedata_data2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='data2',
        ),
    ]
